name = "github-interaction"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

vars = { DEFAULT_REPO_OWNER = "", DEFAULT_REPO = "" }
